inherit_from: configs/default_tet.yaml
method: DenseDecoder
model:
  decoder_kwargs:
    latent_dim: 3
    hidden_dim: 64
    n_blocks: 8
    actvn: gelu
    
data:
  path: datasets/giraffe

training: 
  batch_size: 2048
  print_every: 1
  checkpoint_every: 1000
  validate_every: -1
  checkpoint_dir: checkpoints/tet/giraffe
  saved_checkpoint: null
  
testing:
  best_checkpoint: null
